version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/:/etc/nginx/conf.d
        ports:
            - "3000:80"
        container_name: cuba_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        image: php:8.1
        container_name: cuba_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db

    db:
        image: mysql
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            - MYSQL_USER=$DB_USERNAME
            - MYSQL_PASSWORD=$DB_PASSWORD
            - MYSQL_DATABASE=$DB_DATABASE
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3307:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: cuba_db
volumes:
    tmp:
